// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type ProcdefAddRequest struct {
	Name     string                 `json:"name"`      // 流程名称
	ProcType string                 `json:"proc_type"` // 流程类型
	Data     map[string]interface{} `json:"data"`      // 数据
	Resource map[string]interface{} `json:"resource"`  // 流程内容
}

type ProcdefListRequest struct {
	Current  int64  `form:"current,default=1,optional"`
	PageSize int64  `form:"page_size,default=10,optional"`
	ProcType string `form:"proc_type,optional"`
	Name     string `form:"name,optional"`
}

type ProcdefInfoRequest struct {
	Id string `path:"id"`
}

type ProcessStartRequest struct {
	ProcdefId string `json:"procdef_id"` // 流程id
	Title     string `json:"title"`      // 标题
}

type ProcinstFindListRequest struct {
	Current       int64  `form:"current,default=1,optional"`
	PageSize      int64  `form:"page_size,default=10,optional"`
	ProcType      string `form:"proc_type,optional"`       // 流程类型
	ProcdefName   string `form:"procdef_name,optional"`    // 流程名
	Title         string `form:"title,optional"`           // 标题
	StartTime     int64  `form:"start_time,optional"`      // 开始时间
	EndTime       int64  `form:"end_time,optional"`        // 结束时间
	StartUserName string `form:"start_user_name,optional"` // 开始用户名
	IsFinished    int64  `form:"is_finished,optional"`     // 是否结束
}

type ProcinstInfoRequest struct {
	Id string `path:"id"`
}

type ProcinstCloseRequest struct {
	Id string `path:"id"`
}

type TaskCompleteReq struct {
	TaskId  string `json:"task_id"` // 流程id
	Pass    bool   `json:"pass"`    // 标题
	Comment string `json:"comment"` // 启动添加数据
}

type TaskListByUserIdReq struct {
	Current  int64 `form:"current,default=1,optional"`   //页码
	PageSize int64 `form:"page_size,default=5,optional"` //数据量
}

type GetTokenRequest struct {
	Uid      string `form:"uid"`       // 用户UID
	NickName string `form:"nick_name"` // 用户昵称
	TenantId string `form:"tenant_id"` // 租户ID
}
